name: SeanDinfo
favicon: null
layout_spectrum: 0.6333247059956193
typography_spectrum: 0.7458398751914501
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8076681019738317
  lightness: 0.6332978971768171
  saturation: 0.251551152439788
  rhythmicContrast: 0.587786624673754
purpose: []
