name: SeanDinfo
favicon: null
layout_spectrum: 0.50835
typography_spectrum: 0.61352
title: First Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1c1e'
    - '#43524f'
    - '#637893'
    - '#7fa2b6'
  brandStrength: 0.8076681019738317
  lightness: 0.6332978971768171
  saturation: 0.375
  rhythmicContrast: 0.587786624673754
purpose: []
